indent-width = 4
line-length = 79
required-version = ">=0.11.11"
target-version = "py311"
# Enable preview features.
preview = true
# Содержимое папки alembic-а в проверку не включаем
exclude = ["src/alembic"]

[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true
# Format all docstring code snippets with a line length of 60.
docstring-code-line-length = 60
# Use `\n` line endings for all files
line-ending = "lf"
# Prefer single quotes over double quotes.
quote-style = "single"

[lint]
ignore=["E265", "F811", "D100", "D105", "D104", "D203", "D211", "D213", "N818", "W505", "ANN401"]
select=["E3", "E5", "E4", "E7", "E9", "W", "C90", "I", "N", "D", "F", "ANN", "ASYNC", "A", "COM", "RET", ]

[lint.extend-per-file-ignores]
# Also ignore in all files.
"__init__.py" = ["E402", "E401"]

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.flake8-quotes]
inline-quotes = "single"

[lint.isort]
case-sensitive = true
known-local-folder = ["src"]

[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 10

[lint.pycodestyle]
max-doc-length = 79
# E501 reports lines that exceed the length of 79.
max-line-length = 79
